# Generated by Django 4.0.1 on 2023-06-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False, verbose_name='Id agenda')),
                ('fechaDisp', models.CharField(max_length=8, verbose_name='Fecha de atencion disponible')),
                ('horaDisp', models.CharField(max_length=8, verbose_name='hora de atencion disponible')),
                ('estado', models.CharField(max_length=50, verbose_name='estado de la hora')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspe', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de la especialidad')),
                ('nombreEspe', models.CharField(max_length=50, verbose_name='Nombre de la especialidad')),
                ('fotoEspe', models.ImageField(null=True, upload_to='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key del medico')),
                ('fechaContra', models.CharField(max_length=8, verbose_name='Fecha de contratación del medico')),
                ('sueldo', models.IntegerField(verbose_name='Sueldo del medico')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('idPrevision', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de la previsión')),
                ('nombrePrevi', models.CharField(max_length=50, verbose_name='Nombre de la previsión')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nombreTipo', models.CharField(max_length=10, verbose_name='Admin Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id usuarios')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre Cliente')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('clave', models.CharField(max_length=16, verbose_name='Contraseña')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono de la persona')),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key del paciente')),
                ('idPrevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.prevision')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoEspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEspe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.especialidad')),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.medico')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuario'),
        ),
        migrations.CreateModel(
            name='horaS',
            fields=[
                ('id_horasol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de hora solicitada')),
                ('rutPaciente', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('idAgenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.agenda')),
                ('idEspe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.especialidad')),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.medico')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='idMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.medico'),
        ),
    ]
