# Generated by Django 4.0.1 on 2023-05-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspe', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de la especialidad')),
                ('nombreEspe', models.CharField(max_length=50, verbose_name='Nombre de la especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key del medico')),
                ('rutMedico', models.CharField(max_length=10, verbose_name='Rut del medico')),
                ('fechaContra', models.CharField(max_length=8, verbose_name='Fecha de contratación del medico')),
                ('sueldo', models.IntegerField(verbose_name='Sueldo del medico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key del paciente')),
                ('rutPaciente', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('prevision', models.CharField(max_length=30, verbose_name='Nombre de la prevision')),
                ('especialidad', models.CharField(max_length=30, verbose_name='Nombre de la especialidad del medico')),
                ('nomMedico', models.CharField(max_length=30, verbose_name='Nombre del medico')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de persona')),
                ('rutPersona', models.CharField(max_length=10, verbose_name='Rut de la persona')),
                ('nomPersona', models.CharField(max_length=50, verbose_name='Nombre de la persona')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido/s de la persona')),
                ('correo', models.CharField(max_length=300, verbose_name='Correo de la persona')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono de la persona')),
                ('fechaNac', models.CharField(max_length=8, verbose_name='Fecha de nacimiento de la persona')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('idPrevision', models.AutoField(primary_key=True, serialize=False, verbose_name='La primary key de la previsión')),
                ('nombrePrevi', models.CharField(max_length=50, verbose_name='Nombre de la previsión')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID tipo producto')),
                ('nomTipo', models.CharField(max_length=15, verbose_name='Gato Perro Exotico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('nombreTipo', models.CharField(max_length=10, verbose_name='Admin Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id usuarios')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre Cliente')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('clave', models.CharField(max_length=16, verbose_name='Contraseña')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo')),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoEspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEspe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.especialidad')),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.medico')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.persona'),
        ),
    ]
