# Generated by Django 4.0.4 on 2022-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID tipo producto')),
                ('nomTipo', models.CharField(max_length=15, verbose_name='Gato Perro Exotico')),
            ],
        ),
    ]
